# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Dot"
license = "Creative Commons — Attribution 3.0 Unported — CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Dot, A documentation theme powered by hugo"
homepage = "https://gethugothemes.com/"
tags = ["documentation", "bootstrap", "blog", "contact","responsive", "gethugothemes", "Syntax highlighting " , "Multilingual" , "Single page", "Themefisher"]
features = []
min_version = "0.54"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com"

