name: Update Copyright Notice

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs at midnight on the first day of every year
  workflow_dispatch:

jobs:
  update-copyright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update copyright notice
      run: |
        pwsh -Command "
        $configFilePath = 'config.toml'
        $configContent = Get-Content -Path $configFilePath
        $currentYear = (Get-Date).Year
        $PreviousYear = (Get-Date).Year - 1
        $UpdatedContent = $Content -replace $PreviousYear, $NewYear
        Set-Content -Path $configFilePath -Value $UpdatedContent
        "

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add config.toml
        git commit -m "Update copyright notice for the year $(date +'%Y')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
